const blogs = [
    {
      id: 1,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 2,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 3,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 4,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 5,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 6,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 7,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
    {
      id: 8,
      author: "Avinash Yede",
      title:"This is the title of blog",
      subtitle:"Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      image:
        "https://images.unsplash.com/photo-1691938670117-5c65ae4c19fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&w=800&q=60",
      content:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit.Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquidLorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid,Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid., consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid. Lorem, ipsum dolor sit amet consectetur adipisicing elit. In pariatur quis officia iure id esse quidem explicabo eum rerum doloribus aliquid, consectetur, neque suscipit facere sunt? Porro dolores nisi aliquid.",
    },
  ]

  module.exports = blogs